# Generated by Django 4.1.1 on 2022-09-29 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='dua_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 17, 53, 46, 836713)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('SE', 'secondary'), ('S', 'success'), ('D', 'danger'), ('W', 'warning'), ('I', 'info'), ('L', 'light'), ('D', 'dark')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
