# Generated by Django 4.1.1 on 2022-09-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_dua_date_note_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='dua_date',
            new_name='due_date',
        ),
    ]
